### PR TITLE
Add autorestart on failure

### PR DESCRIPTION
**Pull request by azlux**
The restart isn't done if thelounge stop with a clean exit code

### CODE REVIEW

**Comment by xPaw** [comment]
@brunnre8 What do you think?

**Comment by brunnre8** [comment]
The auto-restart functionality is only truly useful if the program actually exits upon errors.
As far as I know (and please do correct me here) TL rather soldiers on, outputting the error instead of exiting with a non 0 exit code.  
This does make the restart=OnFailure option kinda pointless in my opinion.

@azlux when did TL crash in your case?

**Comment by azlux** [comment]
@brunnre8 Crash ***can*** occur when I do database cleaning and container backup.
Look like TL don't like when the database have small freeze.

Using an autorestart is usefull even if we consider the app is stable.

**Comment by brunnre8** [comment]
Well if you pull out the rug out from under TL then sure...
The proper order of operations if you have a DB dependency for a program and mess with the DB is to stop said service first, then do the cleaning, then restart the service.

@xPaw up to you whether you consider that a good use case or not

**Comment by xPaw** [comment]
I'm gonna agree that if TL crashes it should be inspected. Gonna close this.

**Pull request closed without merging**
