### PR TITLE
Add Provides/Conflicts/Replaces 'lounge' to force removal of the old …

### LINKED ISSUE #48: Replaces
Trying to install v3.0.0-rc.6, there are conflicts with 2.7.1 due to the package name change. I think this warrants a `Replaces` line. Possibly [more](https://wiki.debian.org/RenamingPackages).

### LINKED ISSUE #51: /etc/thelounge/config.js is overwritten on deb update
1. Install rc5
2. Edit config.js
3. Install rc6
4. config.js was reset to default

I'm not entirely sure why that happens as debian considers /etc/ files configs by default.

### PR DESCRIPTION
**Pull request by d7415**
…package.

Fixes #48 
Fixes #51

### CODE REVIEW

**Comment by d7415** [comment]
I'm looking into one other thing...

**Comment by d7415** [comment]
Ok.. So migrating configuration is hard...
- removing `lounge` either manually or automatically deletes the old config.js, which means it's not available for migration.
- the current migration runs as postinst, after /etc/thelounge has been created/populated, so fails its `[ ! -d ]` test and won't execute
- moving the migration to preinst copies successfully, but config.js will be overwritten by the default
- this overwriting already happens on any upgrade

**Comment by d7415** [comment]
> * moving the migration to preinst copies successfully, but config.js will be overwritten by the default
> * this overwriting already happens on any upgrade

The docs I'm reading seem to say this shouldn't happen, but it did in testing.

**Comment by xPaw** [comment]
> the current migration runs as postinst, after /etc/thelounge has been created/populated, so fails its [ ! -d ] test and won't execute

> moving the migration to preinst copies successfully, but config.js will be overwritten by the default

You mean its overwritten by the config that comes in the .deb file? Shouldn't it keep the user file if it exists already on install/upgrade?

> The docs I'm reading seem to say this shouldn't happen, but it did in testing.

Sorry, what docs?

**Comment by xPaw** [comment]
It sounds like we need to add `conffiles`: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

**Comment by xPaw** [comment]
So to reiterate, shouldn't it be enough to move this code to `preinst`: https://github.com/thelounge/thelounge-deb/blob/master/debian/postinst#L42-L46

And that should solve the problem you are describing. Am I misunderstanding?

**Comment by d7415** [comment]
It *should*. I wouldn't mind someone else having another go. For me the config is still overwritten every time (but it does now copy users etc).

I think we'll lose the old config.js anyway (as the old package deletes it on removal), but this way users will be migrated. If the config keeps being overwritten though that might be an issue for future upgrades.

**Comment by xPaw** [comment]
Wow you're right, I just installed rc5, edited the config and installed rc6 and it got overwritten. That definitely should not happen.

**Comment by d7415** [comment]
Ok. conffiles seems to work.

**Comment by xPaw** [comment]
Okay that's nice, thanks for solving this! Good to merge now?

**Comment by d7415** [comment]
I think so. It still won't keep config from the old `lounge` package, but I don't think we can fix that without changing the old package. At least it's only one-time - Might be worth putting in the release notes though.

**Comment by xPaw** [comment]
I just tested that, and it prompts me to diff it so it works as expected:

```
The directory /etc/lounge/ has been moved to /etc/thelounge/
Unpacking thelounge (3.0.0-rc.6-2) ...
Setting up thelounge (3.0.0-rc.6-2) ...

Configuration file '/etc/thelounge/config.js'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** config.js (Y/I/N/O/D/Z) [default=N] ?
```

**Pull request merged**
